apiVersion: v1
kind: Ingress
metadata:
  name: guestbook-ui
  annotations:
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8s.test.crvx.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-ui
          servicePort: 80
